apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
  - host: local.ecosia.org
    http:
      paths:
      - path: /tree
        backend:
          serviceName: ecosia-svc
          servicePort: 8080